apiVersion: v1
kind: Service
metadata:
  name: flexric
  namespace: ric
spec:
  clusterIP: 10.96.100.100
  selector:
    app: flexric
  ports:
    - name: e2ap
      protocol: SCTP
      port: 36421
      targetPort: 36421
