apiVersion: apps/v1
kind: Deployment
metadata:
  name: flexric
  namespace: ric
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flexric
  template:
    metadata:
      labels:
        app: flexric
      annotations:
        k8s.v1.cni.cncf.io/networks: '[
          { "name": "e2network", "interface": "e2", "ips": [ "10.10.4.100/24" ] },
          { "name": "a1network", "interface": "a1", "ips": [ "10.10.5.100/24" ] }
          ]'
    spec:
      containers:
        - name: flexric
          image: ghcr.io/mezlin/flexric:1.0.0
          command: ["/flexric/build/examples/ric/nearRT-RIC"]
          args: ["-c", "/etc/flexric/flexric.conf"]
          ports:
            - containerPort: 36421
              protocol: SCTP
          resources:
            requests:
              cpu: "250m"
              memory: "128Mi"
            limits:
              cpu: "1000m"
              memory: "512Mi"
          volumeMounts:
            - name: config-volume
              mountPath: /etc/flexric/
      volumes:
        - name: config-volume
          configMap:
            name: flexric-config
